name: build

on: [push]

jobs:
  windows:
    strategy:
      matrix:
        r: [devel]
        # r: [3.5, latest, devel]
        python: [3.7]
        # python: [2.7, 3.4, 3.5, 3.6, 3.7]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download R
      run: |
        If ('${{ matrix.r }}' -eq 'latest') {
          (new-object net.webclient).DownloadString("http://cran.rstudio.com/bin/windows/base/") -match 'href="(R-[0-9.]*[a-zA-Z]*-win.exe)"';
          (new-object net.webclient).DownloadFile($("http://cran.rstudio.com/bin/windows/base/"+$matches[1]),"C:\R-binary.exe")
        } ElseIf ('${{ matrix.r }}' -eq 'devel') {
          (new-object net.webclient).DownloadFile("https://cran.r-project.org/bin/windows/base/R-devel-win.exe","C:\R-binary.exe")
        } Else {
          (new-object net.webclient).DownloadString("http://cran.rstudio.com/bin/windows/base/old/") -match 'R (${{ matrix.r }}[\\.0-9]*)</a>'
          (new-object net.webclient).DownloadFile($("https://cran.r-project.org/bin/windows/base/old/"+$matches[1]+"/R-"+$matches[1]+"-win.exe"),"C:\R-binary.exe")
        }
      shell:
        pwsh
    - name: Install R
      run: |
        Start-Process -FilePath "C:\R-binary.exe" -Wait -ArgumentList "/VERYSILENT /DIR=C:\R"
      shell:
        pwsh
    - name: Install reticulate
      run: C:\R\bin\R -e "install.packages('reticulate', repo = 'https://cloud.r-project.org')"
      shell:
        pwsh
    - name: Install and running tests
      run: |
        $env:PATH = "$env:CONDA;$env:CONDA\Scripts;$env:PATH"
        If ('${{ matrix.r }}' -eq '3.4') {
          conda create -y -n myenv python=${{ matrix.python }} -c conda-forge
        } Else {
          conda create -y -n myenv python=${{ matrix.python }}
        }
        activate myenv
        python -m pip install -e .[test]
        python -m pip install jedi
        pytest -s
      shell:
        pwsh
